### ISSUE TITLE
think through high level user interactions

### ISSUE THREAD

**Issue by yujinjcho** [yujinjcho/rcruitme-front#1]
and associated views

**Comment by yujinjcho** [comment]
what do you think about this?

1.  recruiter reaches out to candidate via email or linkedin
2. candidate sends templated response with special link. e.g. "I manage all my recruiting through rcruitme, blah blah, here is link"
3. recruiter clicks link and is directed to create account
4. when recruiter creates account, receives email activation. When they click activation link:
    - create "connection" between recruiter and candidate
    - redirect them to job submit page which is set up for candidate

From there, recruiter home page a list view of submitted jobs with status. They can also receive email notifications when user makes a selection e.g. interested, not interested.

for candidates can just have list of job descriptions where they can select `interested`, `not interested` and maybe optionally provide a reason?

**Comment by yujinjcho** [comment]
some other detail. maybe on the job submit page, there is an option to select a job spec you already created.

**Comment by yujinjcho** [comment]
for now not doing templates. will make job submission per candidate

**Comment by yujinjcho** [comment]
ok so breaking the following into more discrete steps

> candidate sends templated response with special link. e.g. "I manage all my recruiting through rcruitme, blah blah, here is link"

when candidate logs in, they have access to this link. the link will include some form of their user info (wonder if we should use some serialized form of loginInfo or just user id). Also, make constant or add some info so there is some expiration? i.e. so anyone with link can't use it to create connection with the user. maybe given where we are, don't need this right now. I assume the base url should be for our front-end? `localhost:3000` so should we store this in the `application.conf`?

> recruiter clicks link and is directed to create account

The sign up actions will need to pass along the candidate user info. we can either create the connection here or after the recruiter activates their account. 

> when recruiter creates account, receives email activation. When they click activation link:
create "connection" between recruiter and candidate
> redirect them to job submit page which is set up for candidate

need to pass candidate info here into the activation link so the job submit knows who its going to.

**Comment by achiu8** [comment]
Just user id prob fine right? And are you thinking to add serialized timestamp of whenever share link is generated / requested by candidate?

Yeah, I guess we could just hardcode app / frontend root url into `application.conf`.

How are you thinking to pass the candidate user info? We might almost get that for free now with the `redirect` params we've added right. Just need to add to sign-in submit action too. So:
* Attempting to access logged-in page (job submit) while not logged in redirects you to sign-in / sign-up with that initial page as `redirect`
  * Signing up sends activation link with `redirect`; activation controller redirects to `redirect`
  * Signing in with google passes `redirect` as state to google, which redirects to `redirect` after auth
  * Signing in locally redirects you to `redirect` right away

**Comment by yujinjcho** [comment]
sounds good ya lets just do user id
